### ISSUE TITLE
Funding.html isn't showing recent change

### ISSUE THREAD

**Issue by ZeusTheTrueGod** [cncf/landscapeapp#2] opened 2018-12-17 10:07 UTC
https://landscape.cncf.io/selected=gloo

Funding occurred December 10: https://www.crunchbase.com/organization/solo-io#section-overview

Not listed here: https://landscape.cncf.io/funding.html

More bugs here: https://landscape.cncf.io/funding.html

Why -$350 K?

![image](https://user-images.githubusercontent.com/3083270/49875414-f3418000-fdee-11e8-8c25-5c23ab677d1a.png)

**Comment by ZeusTheTrueGod** [comment] 2018-12-27 17:18
I can only check that this is a proper amount on a given date from our processed_landscape.yml.

**Comment by dankohn** [comment] 2019-01-02 21:01
I think this may have been caused by Solo showing a raise of $13.85 one day and then of $13.5 the next day. I'm closing for now until I can come up with a more reproducible use case.

**Closed by dankohn** 2019-01-02 21:01 UTC
Labels: enhancement
